In [9]:
import pandas as pd
df = pd.read_csv('/home/matlab/Documents/jupyter/products-100.csv')
df.head()

,Index,Name,Description,Brand,Category,Price,Currency,Stock,EAN,Color,Size,Availability,Internal ID
0,1,Compact Printer Air Advanced Digital,Situation organization these memory much off.,"Garner, Boyle and Flynn",Books & Stationery,265,USD,774,2091465262179,ForestGreen,Large,pre_order,56
1,2,Tablet,Discussion loss politics free one thousand.,Mueller Inc,Shoes & Footwear,502,USD,81,5286196620740,Black,8x10 in,in_stock,29
2,3,Smart Blender Cooker,No situation per.,"Lawson, Keller and Winters",Kitchen Appliances,227,USD,726,1282898648918,SlateGray,XS,in_stock,70
3,4,Advanced Router Rechargeable,For force gas energy six laugh.,Gallagher and Sons,Kitchen Appliances,121,USD,896,3879177514583,PaleGreen,L,discontinued,31
4,5,Portable Mouse Monitor Phone,Feeling back religious however author room sci...,Irwin LLC,Kids' Clothing,1,USD,925,9055773261265,SeaShell,100x200 mm,discontinued,10

# APPEND TO CSV

In [18]:
new_row={'Index':100,'Name':'lamp','Description':'bright','Brand':'ind','Category':'gadget','Price':464,'Currency':'USD','Stock':823,'EAN':253727724873,'Color':'black','Size':'small','Availability':'in_stock','Internal ID':64}

In [19]:
new_data_df=pd.DataFrame([new_row])

In [25]:
df = pd.concat([df, new_data_df], ignore_index=True)#concating new data frame with existing dataframe

In [24]:
df.to_csv('/home/matlab/Documents/jupyter/products-100.csv', index=False)#new dataframe copied to csv

In [22]:
df.loc[3]=new_row #add in specific position

In [23]:
df.head()

,Index,Name,Description,Brand,Category,Price,Currency,Stock,EAN,Color,Size,Availability,Internal ID
0,1.0,Compact Printer Air Advanced Digital,Situation organization these memory much off.,"Garner, Boyle and Flynn",Books & Stationery,265,USD,774,2091465262179,ForestGreen,Large,pre_order,56
1,2.0,Tablet,Discussion loss politics free one thousand.,Mueller Inc,Shoes & Footwear,502,USD,81,5286196620740,Black,8x10 in,in_stock,29
2,3.0,Smart Blender Cooker,No situation per.,"Lawson, Keller and Winters",Kitchen Appliances,227,USD,726,1282898648918,SlateGray,XS,in_stock,70
3,100.0,lamp,bright,ind,gadget,464,USD,823,253727724873,black,small,in_stock,64
4,5.0,Portable Mouse Monitor Phone,Feeling back religious however author room sci...,Irwin LLC,Kids' Clothing,1,USD,925,9055773261265,SeaShell,100x200 mm,discontinued,10

# read a csv chunk by chunk

In [39]:
from io import StringIO
import pandas as pd
df_chunk = pd.read_csv('/home/matlab/Documents/jupyter/products-100.csv', usecols=["Name", "Brand"])
print(df_chunk.head())

                                   Name                       Brand
0  Compact Printer Air Advanced Digital     Garner, Boyle and Flynn
1                                Tablet                 Mueller Inc
2                  Smart Blender Cooker  Lawson, Keller and Winters
3                                  lamp                         ind
4          Portable Mouse Monitor Phone                   Irwin LLC